// Generated by CoffeeScript 1.9.1
var error, fs;

fs = require('fs');

error = function(code, message) {
  var err;
  err = new Error(message);
  err.code = code;
  return err;
};

module.exports = function(argv, callback) {
  if (!fs.existsSync(argv.source) || !fs.statSync(argv.source).isDirectory()) {
    return callback(error(2, "Input must be a directory"));
  }
  if (!argv.output) {
    return callback(error(1, "No output directory specified"));
  }
  if (!fs.existsSync(argv.output) || !fs.statSync(argv.output).isDirectory()) {
    return callback(error(3, "Output option must be a directory"));
  }
};

//# sourceMappingURL=index.js.map
